### ISSUE TITLE
apply fakeable and tight cuts based on lepton *cone* pt

### ISSUE THREAD

**Issue by muell149** [cms-ttH/ttH-LeptonID#3]
Only for electrons. I will fix this -- It will NOT affect the tight selection.

**Comment by matz-e** [comment]
Do you have a fix for that so far?

**Comment by muell149** [comment]
I do have a fix, but it may be best to wait until the next iteration of synchronization (supposedly ~1week) to make the change. 

@matz-e , do you need the fakeable objects for anything in the meantime?

**Comment by matz-e** [comment]
I do. I have some changes myself for our sync, i think they correspond to what you plan on doing.  Was thinking of posting a PR...

**Comment by muell149** [comment]
Go ahead and do that and I'll check it

**Comment by matz-e** [comment]
I think it may be more than your changes, but from what Thomas said, it sounds like the changes to missing hits you require at the event level anyways.

**Comment by muell149** [comment]
-The cone pt part is correct.
-For the number of missing hits, I think that needs to be kept in the event selection (just like the tight-charge and conversion veto). This does actually have an effect since at event selection we require ==2 tight leptons, and then we place the num missing hits etc cuts on the tight leptons. What does Thomas say?

**Comment by matz-e** [comment]
I'll maybe add that as a flag, and if you switch over to having it in the object definition, we can remove said flag.
